version: '3'
services:

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: user-system
      MYSQL_ROOT_PASSWORD: rootpassword  
    ports:
      - "3307:3306"
    networks:
      - red-interna

  backend:
    build: ./user-management-system
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database 
      DB_PORT: 3306
      DB_DATABASE: user-system
      DB_USERNAME: root
      DB_PASSWORD: rootpassword  
      APP_URL_COMPLETE: http://localhost:8000
      JWT_SECRET: 5roUzpxMfXqDDN3ytktyVEIVE4eF2gh4NyKynlXYEl4UpUjzEWvlRTFeNJ8WxA0Y
    depends_on:
      - database 
    networks:
      - red-interna

  frontend:
    build: ./user-management-system-frontend
    ports:
      - "8001:80"
    depends_on:
      - backend 
    networks:
      - red-interna
      
  

networks:
  red-interna:
    driver: bridge